#Ansible managed, do not touch manually

apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: rke2-coredns
  namespace: kube-system
spec:
  valuesContent: |-
    replicaCount: 2
    
    autoscaler:
      enabled: false
    
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution: []
        preferredDuringSchedulingIgnoredDuringExecution:        
        - weight: 100
          podAffinityTerm:
            topologyKey: "kubernetes.io/hostname"
            labelSelector:
              matchExpressions:
              - key: k8s-app
                operator: In
                values:
                - kube-dns          
